(define (calculator)
  (display "x + y veya çıkış için 'exit' yazın:\n")
  (let ((input (read-line)))
    (if (equal? input "exit")
        (exit)
        (let ((tokens (string-split input " ")))
          (if (= (length tokens) 3)
              (let ((left (string->number (list-ref tokens 0)))
                    (op (list-ref tokens 1))
                    (right (string->number (list-ref tokens 2))))
                (if (and left right)
                    (cond
                      ((string=? op "+") (displayln (+ left right)))
                      ((string=? op "-") (displayln (- left right)))
                      ((string=? op "*") (displayln (* left right)))
                      ((string=? op "/") 
                       (if (= right 0)
                           (displayln "0'a bölünemez!")
                           (displayln (/ left right))))
                      (else (displayln "Hata!")))
                    (displayln "Hata!")))
              (displayln "Hata!")))))
  (calculator))

(calculator)
